services:
  lb:
    image: nathanfabio/fraud-detector4:v13
    command: ["./lb"]
    ports:
      - "9999:80"
    volumes:
      - sock-vol:/run/sock:rw
    depends_on:
      - api1
      - api2
    networks:
      - app-net
    mem_limit: 8m
    cpus: "0.05"
    environment:
      - GOMEMLIMIT=7MiB

  api1:
    image: nathanfabio/fraud-detector4:v13
    command: ["./server"]
    hostname: api1
    volumes:
      - sock-vol:/run/sock:rw
    environment:
      - GOMEMLIMIT=160MiB
      - GOGC=200
    networks:
      - app-net
    mem_limit: 170m
    cpus: "0.475"

  api2:
    image: nathanfabio/fraud-detector4:v13
    command: ["./server"]
    hostname: api2
    volumes:
      - sock-vol:/run/sock:rw
    environment:
      - GOMEMLIMIT=160MiB
      - GOGC=200
    networks:
      - app-net
    mem_limit: 170m
    cpus: "0.475"

volumes:
  sock-vol:

networks:
  app-net:
    driver: bridge
