services:
  lb:
    image: nathanfabio/fraud-detector4:latest
    command: ["./proxy"]
    ports:
      - "9999:80"
    environment:
      - BACKENDS=http://api1:8080,http://api2:8080
    depends_on:
      - api1
      - api2
    networks:
      - app-net
    mem_limit: 20m
    cpus: "0.19"

  api1:
    image: nathanfabio/fraud-detector4:latest
    command: ["./server"]
    environment:
      - PORT=8080
      - GOMEMLIMIT=150MiB
      - GOGC=off
      - GOMAXPROCS=1
    networks:
      - app-net
    mem_limit: 165m
    cpus: "0.405"

  api2:
    image: nathanfabio/fraud-detector4:latest
    command: ["./server"]
    environment:
      - PORT=8080
      - GOMEMLIMIT=150MiB
      - GOGC=off
      - GOMAXPROCS=1
    networks:
      - app-net
    mem_limit: 165m
    cpus: "0.405"

networks:
  app-net:
    driver: bridge
